data_params:
  dataset: "flickr-scenery"
  raw_data_root: "/local/omp/infinityGAN/data/imgs_crop512"
  num_train: 30000
  num_valid: 30000
  lmdb_root: /local/omp/data/infinityGAN-lmdb

train_params:
  data_size: 256
